from app.modules.service_providers.models import IntegrationType, ServiceCategory

DEFAULT_PROVIDERS = [
    {
        "name": "cfe",
        "display_name": "CFE",
        "category": ServiceCategory.ELECTRICITY.value,
        "icon_key": "electricity",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 1,
    },
    {
        "name": "telmex",
        "display_name": "Telmex",
        "category": ServiceCategory.INTERNET.value,
        "icon_key": "internet",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 2,
    },
    {
        "name": "telcel",
        "display_name": "Telcel",
        "category": ServiceCategory.PHONE.value,
        "icon_key": "phone",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 3,
    },
    {
        "name": "izzi",
        "display_name": "Izzi",
        "category": ServiceCategory.INTERNET.value,
        "icon_key": "internet",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 4,
    },
    {
        "name": "totalplay",
        "display_name": "Totalplay",
        "category": ServiceCategory.INTERNET.value,
        "icon_key": "internet",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 5,
    },
    {
        "name": "agua",
        "display_name": "Agua",
        "category": ServiceCategory.WATER.value,
        "icon_key": "water",
        "integration_type": IntegrationType.MANUAL.value,
        "is_active": True,
        "sort_order": 6,
    },
    {
        "name": "gas",
        "display_name": "Gas",
        "category": ServiceCategory.GAS.value,
        "icon_key": "gas",
        "integration_type": IntegrationType.MANUAL.value,
        "is_active": True,
        "sort_order": 7,
    },
    {
        "name": "sky",
        "display_name": "Sky",
        "category": ServiceCategory.TV.value,
        "icon_key": "tv",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 8,
    },
    {
        "name": "megacable",
        "display_name": "Megacable",
        "category": ServiceCategory.TV.value,
        "icon_key": "tv",
        "integration_type": IntegrationType.MOCK.value,
        "is_active": True,
        "sort_order": 9,
    },
]
